services:
  - type: web
    name: crop-yield-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn crop_app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
